### ISSUE TITLE
群聊可以用吗

### ISSUE THREAD

**Issue by Yanyutin753** [Loping151/plugin_readim#1]
有点厉害的哇！

**Comment by Loping151** [comment]
可以的喵，不如说没有分开写群聊和私聊分开的逻辑，读图允许状态也是共享的，也就是说现阶段还存在一个群触发的读图被另一个群用掉了这种问题。

**Comment by Yanyutin753** [comment]
给每个图片搞个专用id,之后就这个id,输入特定指令感觉就可以分开

**Comment by Yanyutin753** [comment]
我电脑搭不起，不然我就去试了😭

**Comment by Loping151** [comment]
图片id不行，得传入群名和用户id建字典打tag。但我的bot基本也不会有多人同时用所以我自己倒是无所谓。。
